# SPDX-FileCopyrightText: Historical upstream contributors
# SPDX-FileCopyrightText: 2026 Chris YO3TCO / Nexus-BS Project
# SPDX-License-Identifier: Apache-2.0 AND PolyForm-Noncommercial-1.0.0
# SPDX-FileComment: Modified by Nexus-BS Project; see CHANGES-NEXUS.md for change notices.

[package]
name = "tetra-pdus"
version.workspace = true
edition.workspace = true
license-file.workspace = true

[dependencies]
tetra-core = { workspace = true }
tetra-saps = { workspace = true }
tetra-config = { workspace = true }
tracing = { workspace = true }
